version: "3.9"
services:
  meta-game-pg:
    container_name: "meta-game-pg"
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: always
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_CONNECTION_STRING=mongodb+srv://soumya:5SPPibFbgO@cluster0.bscpenz.mongodb.net/metagame-pg?retryWrites=true&w=majority
    volumes:
      - ./server:/app/
      - /app/node_modules
